### ISSUE TITLE
Error when querying for validators

### ISSUE THREAD

**Issue by packetstracer** [fetchai/fetchd#132]
I've just installed fetchd and get an error when executing a command to get the validators

Command:
`fetchd query staking validators`

Error:
`Error: error unmarshalling result: unknown field "proof" in types.ResponseQuery`

Fetchd version:
`fetchd version --long`

```
name: fetch
server_name: <appd>
version: 0.8.1-4-g4b7f792
commit: 4b7f792375bb17a91a34b49bd006d7c831d35c8c
build_tags: netgo,ledger
go: go version go1.16.5 linux/amd64
```

Steps to reproduce the error:

```sh
mkdir ~/fetch && cd ~/fetch
git clone https://github.com/fetchai/fetchd.git && cd fetchd
make build
make install
fetchd query staking validators
```

**Comment by daeMOn63** [comment]
Have you configured it with the network you want to reach before issuing queries ? (see [docs/docs/cli-introduction.md](https://github.com/fetchai/fetchd/blob/master/docs/docs/cli-introduction.md)). We're currently in the process of upgrading fetchd to  the `stargate` version of cosmos-sdk, and some docs are still not updated (ie: `fetchcli` have disappeared and you must use `fetchd` instead now)

Also note that currently, master branch holds a fetchd version to connect to `stargate` networks (see [our available networks](https://github.com/fetchai/fetchd/blob/master/docs/docs/networks.md)). If you instead want to connect to our `mainnet`, you'll have to checkout the [v0.7.4](https://github.com/fetchai/fetchd/tree/v0.7.4) tag first and rebuild. You'll still need to configure it as mentioned in the above documentation prior to querying things.

**Comment by packetstracer** [comment]
Yes I was using the docs but using fetchd because I saw you depecrated it in previous releases. I did configure the client to the testnet before querying.

```sh
fetchd config chain-id fetchhubtest-1
fetchd config node https://rpc-fetchhubtest.prod.fetch-ai.com:443
```

Ok, I'll downgrade to v0.7.4 tag and try again.

**Comment by daeMOn63** [comment]
Did that work @packetstracer? Can we close?

**Comment by packetstracer** [comment]
Yes. Worked with v0.7.4

**Comment by packetstracer** [comment]
> Did that work @packetstracer? Can we close?

Yes. Worked with v0.7.4
