### ISSUE TITLE
make build command with errors

### ISSUE THREAD

**Issue by samuraya** [fetchai/fetchd#158]
"make build" command returns two errors "/go/pkg/mod/github.com/fetchai/cosmos-sdk@v0.17.6/x/evidence/exported/evidence.go:28:2: duplicate method String"

**Comment by daeMOn63** [comment]
Can you try running `go clean -cache` and retry ?

If it doesn't help, can you share a bit more details on your setup ? OS / go version / fetchd version you're trying to build...

**Comment by samuraya** [comment]
tried go clean -cache. didnt help. attached is the screenshot of error.

My system setup is
* Linux Mint 20.2 Cinnamon
* go version go1.13.8 linux/amd64
* fetchd is current master branch cloned from repo.


![image](https://user-images.githubusercontent.com/61466437/133544670-5b9bdf6d-6388-4863-936d-d6f97689757c.png)

**Comment by daeMOn63** [comment]
Ok looks like you're `go 1.13` version is too old, you'll need at least `go1.16`

**Comment by daeMOn63** [comment]
Looks like fixed, closing for now, feel free to open new issues if you still have troubles
