### ISSUE TITLE
issue with agent-land network

### ISSUE THREAD

**Issue by samuraya** [fetchai/fetchd#159]
This might not be the right repo to mention regarding the Agent-Land testnet but I have already raised my issue over there and realized nothing much going on in there (no engagement). 

The issue is that the agent-land network seem to have problems generating funds for fetchai user, both over CLI and website "https://explore-agent-land.fetch.ai/". Anyone over here happen to know anything about this? 

I like the project and want fetch to succeed but the lack of info and guides for devs makes it hard to fully utilize fetch's capabilities.

**Comment by daeMOn63** [comment]
This network is now considered deprecated. We're currently in the process of upgrading our networks and applications to uses the latest cosmos versions. Docs and guides will follow, please be patient :)

**Comment by samuraya** [comment]
cool : ) thanks
