### ISSUE TITLE
Node startup failed

### ISSUE THREAD

**Issue by blocknodehub** [fetchai/fetchd#217]
I failed to start node with v0.10.2 version
I use this genesis file 【https://raw.githubusercontent.com/fetchai/genesis-fetchhub/main/fetchhub-4/data/genesis_migrated_5300200.json】
![截屏2022-04-13 18 32 34](https://user-images.githubusercontent.com/100512407/163161610-fb762ea6-7117-4699-8800-31fe89c644d2.png)

**Comment by daeMOn63** [comment]
Hi, can you try running `fetchd unsafe-reset-all` and restarting the node again? The node needs a clear state to read the genesis file, otherwise, it just ignores it and continues with its existing state.
