### ISSUE TITLE
Broadcast transaction got Error

### ISSUE THREAD

**Issue by Wangmmx** [fetchai/fetchd#231]
Hi, I broadcast FET tx got error since yesterday, the error is `Error: Error: 0ufet is smaller than 20ufet: insufficient funds: insufficient funds`, but my sender's address has FETs in it, is there some upgrade?
Transaction hex is 
`0a8a010a87010a1c2f636f736d6f732e62616e6b2e763162657461312e4d736753656e6412670a2c6665746368316335396c35326138613733667366776138677233786e7275373237327871333865336c743365122c66657463683161393667346d73777737356d35636d707a39337561726a3978796630376b766b776d6636346c1a090a047566657412013812640a500a460a1f2f636f736d6f732e63727970746f2e736563703235366b312e5075624b657912230a21035a27b3564c6a08337ba07f8120551d5721e9ae888bcd60df705de7509d2bc73d12040a020801180a12100a0a0a04756665741202323010c09a0c1a408438798a3cb2123234b127db64352898a207cd447c9c4b49b8b3a775989c1ae200b154d48c0d390d8aa7594b0cd8898ca0ae89e3bea97efbf4981e22fd02e1a4`

sender: fetch1c59l52a8a73fsfwa8gr3xnru7272xq38e3lt3e

**Comment by daeMOn63** [comment]
Looks fixed, I can see recent txs from the mentioned account.
The above error seems to originate from a wrong denomination used (`ufet` != `afet`) - correct one being `afet`
