### ISSUE TITLE
Feature request: Only mine on new transaction

### ISSUE THREAD

**Issue by dishmop** [fetchai/fetchd#236]
### Prerequisites

- [X] I checked the [documentation](https://docs.fetch.ai/ledger_v2/cli-introduction/) and made sure this feature does not already exist.
- [X] I checked the [existing issues](https://github.com/fetchai/fetchd/issues) to make sure this feature has not already been requested.

### Problem

Development is very slow or very resource intensive. 

If I run a local fetchd node with default (5 second) block times then it can take minutes to run through a single scenario using cosmpy. This means our integration tests can take half an hour.

If I set skip_timeout_commit = true in the config then I get much faster mining, but it quickly uses up large amounts of disc space.

### Feature / Solution

I want to not mine blocks until a transaction comes in and then immediately mine (ganache does this)

**Comment by daeMOn63** [comment]
This can be achieved setting:
```
# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = false
```

in `~/.fetchd/config.toml`
