### ISSUE TITLE
Bug report: Sending transactions with block explorers on Eridanus

### ISSUE THREAD

**Issue by bryanchriswhite** [fetchai/fetchd#270]
### Prerequisites

- [X] I am running the [latest fetchd version](https://docs.fetch.ai/ledger_v2/versions/).
- [X] I checked the [documentation](https://docs.fetch.ai/ledger_v2/cli-introduction/) and found no answer to my problem.
- [X] I checked the [existing issues](https://github.com/fetchai/fetchd/issues) to make sure my problem has not already been reported.

### Expected Behavior

Users should be able to send transactions from block explorers and dapps running on the Eridanus network.

### Current Behavior

@daeMOn63, can you elaborate?

### Context

@daeMOn63, can you elaborate?

**Comment by daeMOn63** [comment]
@bryanchriswhite this should belong to the https://github.com/fetchai/cosmos-explorer repo, tracked by https://github.com/fetchai/cosmos-explorer/pull/170

**Comment by bryanchriswhite** [comment]
Thanks for explaining @daeMOn63!
