### ISSUE TITLE
Mobile SOEF on P2P_lib on 5G / modified Exposure Notifications API

### ISSUE THREAD

**Issue by KY-BChain** [fetchai/fetchd#50]
Years ago people use their laptops on email that is cool.
Today, everything is mobile based.
AEA must have options to be on mobile SOEF on P2P_lib on 5G / modified Exposure Notifications API.
Such as Status, Helium for example

**Comment by daeMOn63** [comment]
Looks like wrong repo, did you meant to post on https://github.com/fetchai/agents-aea ?
