### ISSUE TITLE
Malformed fetchcli request when trying to stake

### ISSUE THREAD

**Issue by eorituz** [fetchai/fetchd#74]
I ran into an issue when trying to stake tokens on the AW1 testnet. 
```
root@fetch:~/fetchd# fetchcli tx staking delegate fetchvaloper108hhutnylgz09acca2ljde8dp6huhsu67hn8v7 900atestfet --from agent
Enter keyring passphrase:
ERROR: cannot parse disfix JSON wrapper: json: cannot unmarshal string into Go value of type amino.disfixWrapper
```
My key is imported and configured properly (I'll post it anyway for the sake of completness):
```
root@fetch:~/fetchd# fetchcli keys list
Enter keyring passphrase:
- name: agent
  type: local
  address: fetch1yvk5jz8y4h7pftxeherf76utl6yk5mra034e2g
  pubkey: fetchpub1addwnpepq2ymtpp9a8metv3982j3kpazc842xe7r6egdxwq4frnz3rrcswn45tft9nx
  mnemonic: ""
  threshold: 0
  pubkeys: []
```

My best guess is that the fetchcli posts a malformed request because a similar issue has been opened in the cosmos SDK:
https://github.com/cosmos/cosmos-sdk/issues/3743

```
root@fetch:~/fetchd# fetchcli status
{"node_info":{"protocol_version":{"p2p":"7","block":"10","app":"0"},"id":"1832bda19fed5785afcd4767f5ccdb1d9e0df601","listen_addr":"tcp://127.0.0.1:26656","network":"agentworld-1","version":"0.33.3","channels":"4020212223303800","moniker":"Bond","other":{"tx_index":"on","rpc_address":"tcp://127.0.0.1:26657"}},"sync_info":{"latest_block_hash":"C5FD08A60C49B7334AE882121FC231D04D2286029793EF530C69302A8528CED0","latest_app_hash":"0D20528BB629E75B430DCC5A3FAF4AA0FE926CF2DF4BEC3A4F8A0878CC41D415","latest_block_height":"2029362","latest_block_time":"2021-03-02T13:30:00.431689059Z","earliest_block_hash":"","earliest_app_hash":"","earliest_block_height":"0","earliest_block_time":"0001-01-01T00:00:00Z","catching_up":false},"validator_info":{"address":"D15C2986B4D68422BBF6319BFCDE1415DE370E48","pub_key":{"type":"tendermint/PubKeyEd25519","value":"46KurFbOwziJefIjS5bEDBl0NYxyuuzvt2t0ulKxa94="},"voting_power":"0"}}
```
```
root@fetch:~/fetchd# fetchcli version
0.6.1-1-g6729bba
```

### Edit
I just tried to do a regular tx using the fetchcli and ran into the same error message.
So maybe it's an issue with my local installation but I have no clue how to tackle that problem....
---> I reinstalled go, its dependencies, and fetchcli 3 times without any success

**Comment by daeMOn63** [comment]
I did run into a similar issue as well. Looks like any CLI version above `v0.2.7` won't work on `agent-land` and `agent-world` networks. You can try using an older release of the CLI or switch to the beacon-world network.

Have a look at https://github.com/fetchai/fetchd/blob/master/docs/docs/networks.md for the versions supported by each network

**Comment by eorituz** [comment]
@daeMOn63 Thanks for the update!
It would be great to update the compatible versions in https://github.com/fetchai/fetchd/blob/master/docs/docs/networks.md and make it somewhat more visible in the docs what versions are required.
E.g. give a range of compatible CLI versions because 0.6.x is not mentioned atm. 

A bit off-topic:
Maybe you could update the links in the [Beacon World 1 section of the incentivized testnet](https://docs.fetch.ai/i_nets/quickstart-bw1/). As of now, they point to the AW1 testnet block explorer. Therefore I assumed staking in AW1 is required to complete the task.

**Comment by daeMOn63** [comment]
Thank you for the suggestions! I added more explicit CLI versions in the network page and updated the BW1 page in the doc repository. Hope this helps!
