### ISSUE TITLE
daemon stopped at 116263 height

### ISSUE THREAD

**Issue by Yurbason** [fetchai/fetchd#96]
fetchd[4842]: panic: Failed to process committed block (116263:BB091EED72F1E54FCC1E8AB65F3502319327418576656592D4F59FE7BF200820): wrong Block.Header.AppHash.  Expected DD2A6C7057BED250C67D814A7166980701C1106A52CD898297F81155446ABC36, got 38B5599B7EABA50564D660DB12B51A115813416D341D779F341084EB1F7058D7

Apr 08 19:58:59 systemd[1]: Started Fetch Validator.
Apr 08 19:58:59 fetchd[5804]: I[2021-04-08|19:58:59.736] starting ABCI with Tendermint                module=main
Apr 08 19:59:00 fetchd[5804]: ERROR: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected DD2A6C7057BED250C67D814A7166980701C1106A52CD898297F81155446ABC36, got 38B5599B7EABA50564D660DB12B51A115813416D341D779F341084EB1F7058D7
Apr 08 19:59:00 systemd[1]: fetchd.service: Main process exited, code=exited, status=1/FAILURE
Apr 08 19:59:00 systemd[1]: fetchd.service: Failed with result 'exit-code'.
Apr 08 19:59:01 systemd[1]: Stopped Fetch Validator.

fetchd version --long
name: fetch
server_name: fetchd
client_name: fetchcli
version: 0.7.2
commit: f49ffed4c53d7e4c18b2197dad87633f6d0bec2a
build_tags: netgo,ledger
go: go version go1.15.6 linux/amd64

unsafe-reset-all didnt helped

**Comment by Yurbason** [comment]
fetchd version --long
name: fetch
server_name: fetchd
client_name: fetchcli
version: 0.7.2-3-g23b5f92
commit: 23b5f92b16783a55800fdd6632eee69674f0e143
build_tags: netgo,ledger
go: go version go1.15.6 linux/amd64

updating to the last commit did not solve the problem

**Comment by daeMOn63** [comment]
Could you please retry syncing a node with v0.7.3 ? There was a bug in tendermint making the hash validation fail in some cases.

**Comment by Yurbason** [comment]
> Could you please retry syncing a node with v0.7.3 ? There was a bug in tendermint making the hash validation fail in some cases.

if I try to sync from the first block, it will take a very long time and my validator will go to jail :(
I will try to update and continue from the current block

**Comment by Yurbason** [comment]
updated to 0.7.3
works without errors, I will monitor

**Comment by daeMOn63** [comment]
Looks all fine now, I'll close the issue. Please reach out if you have any problems!
